language: php

php:
  - 7.0

env:
  global:
    - setup=basic

matrix:
  fast_finish: true
  include:
    - php: 5.5.9
      env: setup=lowest

sudo: false

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - vendor/bin/phpunit tests/classes
  - vendor/bin/phpunit tests/controllers/batch1
  - vendor/bin/phpunit tests/controllers/batch2
  - vendor/bin/phpunit tests/helpers
  - vendor/bin/phpunit tests/models
  - vendor/bin/phpunit tests/relationships
  - vendor/bin/phpunit tests/ui